# Generated by Django 3.1.4 on 2022-06-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='items_media')),
                ('qnt', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=20)),
                ('price', models.FloatField(default='set by agreement')),
            ],
        ),
    ]
